version: 2
jobs:
    build: &build
      docker:
        - image: sicz/dockerspec
      steps:
        - checkout
        - run:
            name: Checkout make files
            command: |
              cd ..
              curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
              mv Mk-master Mk
        - setup_remote_docker:
            version: 17.06.0-ce
        - run:
            name: Build and test Docker image
            command: |
              cd ${CI_DIR}
              make ci
        - deploy:
            name: Save Docker image to workspace
            command: |
              cd ${CI_DIR}
              mkdir -p /tmp/workspace
              make docker-save-image DOCKER_IMAGE_DEPOT=/tmp/workspace
              ls -lh /tmp/workspace
        - persist_to_workspace:
            root: /tmp/workspace
            paths:
              - "*.image"

  8u141-jre-alpine:
    <<: *build
    environment:
      - CI_DIR=8u141/jre-alpine
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc

  8u141-jdk-alpine:
    <<: *build
    environment:
      - CI_DIR=8u141/jdk-alpine
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc

  8u141-jre-centos:
    <<: *build
    environment:
      - CI_DIR=8u141/jre-centos
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc

  8u141-jdk-centos:
    <<: *build
    environment:
      - CI_DIR=8u141/jdk-centos
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc

  publish:
    docker:
      - image: sicz/dockerspec
    environment:
      - MAKEFLAGS=--no-print-directory
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Checkout make files
          command: |
            cd ..
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master Mk
      - attach_workspace:
          at: /tmp/workspace
      - deploy:
          name: Push images to the Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              make docker-load-image DOCKER_IMAGE_DEPOT=/tmp/workspace
              docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWD}
              make docker-push
            fi

workflows:
  version: 2

  build:
    jobs:
      - 8u141-jre-alpine
      - 8u141-jdk-alpine:
          requires:
            - 8u141-jre-alpine
      - 8u141-jre-centos:
          requires:
            - 8u141-jre-alpine
      - 8u141-jdk-centos
      - publish:
          requires:
            - 8u141-jre-alpine
            - 8u141-jdk-alpine
            - 8u141-jre-centos
            - 8u141-jdk-centos
