version: 2
jobs:
  build:
    docker:
      - image: sicz/dockerspec@sha256:217e4ee091029d09ade6f82d6a58c2c7b5c00519c287cda49c13f142c26d26fe
    environment:
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Remote Docker engine version and images
          command: |
            docker version
            docker image ls
      - run:
          name: Checkout make files
          command: |
            cd ..
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master Mk
      - run:
          name: sicz/openjdk:8u141-jre-alpine
          working_directory: 8u141/jre-alpine
          command: |
            make ci
      - run:
          name: sicz/openjdk:8u141-jdk-alpine
          working_directory: 8u141/jdk-alpine
          command: |
            make ci
      - run:
          name: sicz/openjdk:8u141/jre-centos
          working_directory: 8u141/jre-centos
          command: |
            make ci
      - run:
          name: sicz/openjdk:8u141/jdk-centos
          working_directory: 8u141/jdk-centos
          command: |
            make ci
      - deploy:
          name: Push images to the Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWD}
              make docker-push
            fi
