### DOCKER_VERSIONS ###########################################################

DOCKER_VERSIONS		?= jre-alpine \
			   jdk-alpine \
			   jre-centos \
			   jdk-centos

### MK_DOCKER_IMAGE ############################################################

PROJECT_DIR		?= $(abspath ..)
include $(PROJECT_DIR)/docker.variant.mk

################################################################################
